### ISSUE TITLE
ShapeMapper2 stops calculations

### ISSUE THREAD

**Issue by angelika888** [Weeks-UNC/shapemapper2#15]
Hi,
My operating system is Linux Ubuntu. First, after instalation I ran run_example.sh file and everything worked. When I tried use example data from SRA in fastq format I get always issue as below (always at 21% withous any comment):

----------------------------------------------------------------------------
Started ShapeMapper v2.1.5 at 2020-04-21 18:06:18
Output will be logged to RUN20042020_shapemapper_log.txt
Running from directory: /home/angelika/shapemapper-2.1.5
args:  --overwrite --name RUN20042020 --target 20042020/Reference.fasta --out RUN20042020_shapemap --random-primer-len 9 --star-aligner --modified --folder 20042020/Treated_1M7 --untreated --folder 20042020/Untreated_DMSO --denatured --folder 20042020/Denatured_1M7
Created pipeline at 2020-04-21 18:06:18
Running FastaFormatChecker at 2020-04-21 18:06:18 . . .
. . . done at 2020-04-21 18:06:18
Running StarIndexBuilder at 2020-04-21 18:06:18 . . .
. . . done at 2020-04-21 18:06:19
Running process group 3 at 2020-04-21 18:06:19 . . .
  Including these components:
    ProgressMonitor . . . started at 2020-04-21 18:06:19
    QualityTrimmer1 . . . started at 2020-04-21 18:06:19
    QualityTrimmer2 . . . started at 2020-04-21 18:06:19
    Interleaver . . . started at 2020-04-21 18:06:19
    Merger . . . started at 2020-04-21 18:06:19
    Deinterleaver . . . started at 2020-04-21 18:06:19
    StarAligner_paired . . . started at 2020-04-21 18:06:19
    StarAligner_unpaired . . . started at 2020-04-21 18:06:19
    SamMixer . . . started at 2020-04-21 18:06:19
    MutationParser_Modified . . . started at 2020-04-21 18:06:19
    MutationCounter_Modified . . . started at 2020-04-21 18:06:19
  273MiB [============>                                                   ] 21% ETA 0:16:46    
 ShapeMapper run failed at 2020-04-21 18:11:03.
-----------------------------------------------------------------------------
Before this, I had problem with fastq format, but I resolved it like here:
https://github.com/Weeks-UNC/shapemapper2/issues/10

And after this I have this issue.

It will be great if you will take a look on this.

Regards,
Angelika

**Comment by shapemapper** [comment]
First thing to check is whether the input FASTQ files are complete.

1) Do the R1 and R2 files have the same number of lines?
If the files are uncompressed, check with a command like `wc -l filename_R1.fastq`
"wc" is short for the "word count" utility, and the "-l" option counts lines.
If files are compressed, use a command like `zcat filename_R1.fastq.gz | wc -l`
2) Do the file formats look correct?
Inspect the first few reads in both R1 and R2 files with a command like `head -n 16 name_R1.fastq`
Also take a look at the last few reads with a command like `tail -n 16 name_R1.fastq`
If files are compressed, use something like `zcat name_R1.fastq.gz | tail -n 16`

If there isn't something immediately unusual about the input files, then I would try rerunning shapemapper with the "--verbose" and "--serial" options to help pinpoint the problem.

**Comment by angelika888** [comment]
Thank you for advices. I'll check all these things :)
I hope the problem doesn't appear again.

Regards,
Angelika

**Comment by angelika888** [comment]
Indeed, this problem occured because of incomplete input FASTQ files :)

**Comment by eoziolor** [comment]
Thank you!!!
