### ISSUE TITLE
superfold software

### ISSUE THREAD

**Issue by eoziolor** [Weeks-UNC/shapemapper2#16]
Hi! First of all, thank you for providing such great tools!

I am trying to find/use SuperFold software linked in your other_software.md, but the link (https://weeks.chem.unc.edu/software.html) placed in your markdown is not functional and I haven't been able to find the software or any manuals for it. Would you be able to point me to the software/use cases for it?

Thank you!

-Elias

**Comment by Psirving** [comment]
Hello, thanks for bringing this up. The old lab website has been taken down, you can find links to our software here:
https://weekslab.com/software/

and specifically SuperFold here:
https://webshare.oasis.unc.edu/weeksgroup/Superfold_v1.0.tar.gz

This is the paper that discusses the original ShapeMapper and SuperFold:
https://www.ncbi.nlm.nih.gov/pubmed/26426499

I'll update these links in the markdown.

Thanks!
-Patrick

**Comment by eoziolor** [comment]
Fantastic, thank you very much Patrick! This is a really nice resource, I appreciate the quick pointer!
