### ISSUE TITLE
Median Rate Bug

### ISSUE THREAD

**Issue by twchrist** [Weeks-UNC/shapemapper2#2]
It appears that in the histograms pdf, the median rates reported are not actually the median rates but are probably the 5th percentile mutation rates.
[C8Mg_rnasep_histograms.pdf](https://github.com/Weeks-UNC/shapemapper2/files/2601545/C8Mg_rnasep_histograms.pdf)

**Comment by shapemapper** [comment]
fixed in 2.1.5
