### ISSUE TITLE
an advice please

### ISSUE THREAD

**Issue by tanasa** [Weeks-UNC/shapemapper2#21]
Dear ShapeMapper2 authors, 

please may i ask for a piece of advice: we have recently obtained ShapeMap data, and i have just started to set up the pipeline with ShapeMapper2.1.5. The provided example works fine, however on the data we have, it gives the message : 

================================================
Traceback (most recent call last):
  File "/media/bogdan/e7a05079-e4ce-4cfa-b0cd-bf2d7a54b46d/shapemapper-2.1.5_runs_B/internals/python/pyshapemap/locate_primers.py", line 209, in <module>
    pa.primers_in_sequence)
  File "/media/bogdan/e7a05079-e4ce-4cfa-b0cd-bf2d7a54b46d/shapemapper-2.1.5_runs_B/internals/python/pyshapemap/locate_primers.py", line 125, in locate_primer_pairs
    raise RuntimeError("Error: Could not find lowercase sequence indicating amplicon primers.")

RuntimeError: Error: Could not find lowercase sequence indicating amplicon primers.

thank you very much ! with much appreciation, 

-- bogdan

**Comment by Psirving** [comment]
Hello Bogdan,

If you use the `--amplicon` flag, you need to either give it a primers file or indicate the location of the primers in the fasta file by making those nucleotides lowercase. View the README for more info. Let me know if this doesn't fix the issue.

-Patrick

**Comment by tanasa** [comment]
Dear Patrick, awesome, thank you for the quick reply ! yes, i am going again over the documentation, and will let you know :) 

with much appreciation, 

-- bogdan

**Comment by tanasa** [comment]
Thank you very much Patrick. The pipeline is running well, although we need to optimize it and scan several sets of parameters :).

shall we have more questions regarding the parameters, could we email you, or shall i post the questions on github ? thanks a lot !

**Comment by Psirving** [comment]
You can email me with those types of questions. psirving@email.unc.edu
