### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rotruebchen** [Weeks-UNC/shapemapper2#25]
Hello Shapemapper2 team, 

I have encountered the follow error message with the dataset that I am currently trying to analyze and would like to ask if you have any idea what the source of the issue is and how it can be fix it.
Thanks a lot for your help. 

**Warning: no random primer length was specified, but at least one RNA is longer than a typical directed-primer amplicon. Use --random-primer-len to exclude mutations within primer binding regions.**
Created pipeline at 2021-11-22 18:03:58
Running FastaFormatChecker at 2021-11-22 18:03:58 . . .
. . . done at 2021-11-22 18:03:59
Running BowtieIndexBuilder at 2021-11-22 18:03:59 . . .
. . . done at 2021-11-22 18:03:59
Running process group 3 at 2021-11-22 18:03:59 . . .
  Including these components:
    ProgressMonitor . . . started at 2021-11-22 18:03:59
    QualityTrimmer1 . . . started at 2021-11-22 18:03:59
    QualityTrimmer2 . . . started at 2021-11-22 18:03:59
    Interleaver . . . started at 2021-11-22 18:03:59
    Merger . . . started at 2021-11-22 18:03:59
    LengthFilter . . . started at 2021-11-22 18:03:59
    BowtieAligner . . . started at 2021-11-22 18:03:59
    MutationParser_Modified . . . started at 2021-11-22 18:03:59
    MutationCounter_Modified . . . started at 2021-11-22 18:03:59
Traceback (most recent call last):
  File "/programs/x86_64-linux/shapemapper2/2.1.3/python/cli.py", line 108, in <module>
    run(sys.argv)
  File "/programs/x86_64-linux/shapemapper2/2.1.3/python/cli.py", line 65, in run
    success = pipeline.run()
  File "/programs/x86_64-linux/shapemapper2/2.1.3/python/pyshapemap/pipeline.py", line 743, in run
    s = self.get_error_message(run_group)
  File "/programs/x86_64-linux/shapemapper2/2.1.3/python/pyshapemap/pipeline.py", line 590, in get_error_message
    msg += c.get_error(verbose=verbose)
  File "/programs/x86_64-linux/shapemapper2/2.1.3/python/pyshapemap/component.py", line 565, in get_error
    s += "\n" + self.read_stderr()
  File "/programs/x86_64-linux/shapemapper2/2.1.3/python/pyshapemap/component.py", line 469, in read_stderr
    f = open(self.stderr.output_nodes[0].filename, 'rU')
**FileNotFoundError: [Errno 2] No such file or directory: 'shapemapper_temp/XYZ/Modified/ProgressMonitor/XYZ_Modified_ProgressMonitor_stderr.txt'**

**Comment by ixeft** [comment]
For people that encounter this message : It means that some input file were not found, check your input file path ;)
