### ISSUE TITLE
ShapeMapper using PACBIO

### ISSUE THREAD

**Issue by dksenthil** [Weeks-UNC/shapemapper2#27]
Hi, Does the tool accept PACBIO fastq files? I see that it is not currently supported (based on the FAQ) But its there any plans to incorporate it?

**Comment by Psirving** [comment]
Sorry for not replying sooner. There are currently no plans from our lab to incorporate PACBIO reads. If this becomes a more common sequencing platform for SHAPE-MaP experiments, we might revisit this.
