### ISSUE TITLE
ShapeMapper run failed while MutationCounter_modified

### ISSUE THREAD

**Issue by amkilar** [Weeks-UNC/shapemapper2#29]
Hello,

I'm trying to run fastq files with ShapeMapper2 and for raw data it works perfectly. However, if I first run preprocessing with FASTX (trimming and quality-based filtering) and then Shapemapper, it fails without any specified error always very close to the end (97-100%) of _MutationCounter_modified_ calculation.

Primarily, I thought that it might be a problem with the different lengths of the reads, but made them the same length and it didn't solve the issue. 

I would appreciate any help.

**Comment by Psirving** [comment]
Sorry for not replying sooner. Did you find a solution to this issue?

**Comment by amkilar** [comment]
Unfortunately, the problem persists also after processing raw reads with TRIMMOMATIC, instead of FASTX. 
Again, I checked for different lengths of R1 and R2, but they are the same.

![image](https://user-images.githubusercontent.com/27952166/188180296-0d0e79f6-5af7-442e-a90f-9d5079ca0c1a.png)

**Comment by Psirving** [comment]
Sorry, I can't say exactly what is happening here. Failing without error makes this very hard to diagnose.

You said that the pipeline works fine for untrimmed/unfiltered reads. If that is the *only* thing that is changing, it makes me think that Shapemapper2 is taking issue with the format of your input reads. However, usually it will catch errors in format long before it gets to MutationCounter.

It might be that it Shapemapper2 is failing with some interaction between modules. Try running the pipeline without `--render-flowchart --render-mutations --per-read-histograms --output-processed-reads --output-aligned-reads --output-parsed-mutations --output-counted-mutations`.

If that doesn't work, check your fastq files. Check the number of lines. Check the fastq format at the top and bottom of the file using head/tail. Fastq file names should match exactly save the _R1_/_R2_ field. There should be no other fastq files in the folder. The 3rd line of each fastq entry should contain only a '+'. Run FASTQC on pre/post-FASTX files to make sure there aren't any glaring issues with the sequences or qualities. (this is good practice in general before running Shapemapper2).

Let me know how this goes and if you find out anything.

**Comment by amkilar** [comment]
Thank you for your response and help!

My _trimmomatic_ run resulted in creating trimmed reads **and** unpaired reads. It seems to cause me further issues with Shapemapper2. I removed unpaired reads from the folder, and it solved the problem.
