### ISSUE TITLE
workflow runs very slow

### ISSUE THREAD

**Issue by AbeerMM** [Weeks-UNC/shapemapper2#36]
Hi,

I'm running shapemapper2, and it's taking very long although I'm using 45 threads. Below is some context on my run.

I have my gzipped files with the following sizes:
Modified: R1 ~1.8 GB, R2 ~1.8GB
Untreated:  R1 ~1.6 GB, R2 ~1.6GB
Denatured:  R1 ~1.5 GB, R2 ~1.5GB

I ran this command to start Shapemapper2: 
`shapemapper --name $prefixStr --target $targ_seq --out $outName --modified --R1 $treated_R1 --R2 $treated_R2 --untreated --R1 $untreated_R1 --R2 $untreated_R2 --denatured --R1 $denatured_R1 --R2 $denatured_R2 --nproc 45 --verbose --preserve-order --output-processed-reads --output-aligned-reads --output-parsed-mutations --output-counted-mutations --render-flowchart --render-mutations --per-read-histograms`

The alignment process (default/bowtie2) is taking too long even though I'm running the pipeline on EC2 with 45 threads. The Modified samples took 13hrs to get these files:

- \<sampleName\>_Modified_aligned.sam 
- \<sampleName\>_mutation_counts.txt
- \<sampleName\>_Modified_BowtieAlignerMixedInput_Tab6Interleaver_SplitToFile1_tab6.tab6
- \<sampleName\>_parsed.mut
 
Is it normal to run that long with multiple number of threads (45)? I think shapemapper1 was a bit faster.
Is there anything I could do to make it run faster or reduce the time a few hours less?
 
Thank you

**Comment by AbeerMM** [comment]
Thanks for your response, @Psirving. I changed the instance type, and it seems it's running fine now. The run is at this step:
shapemapper_mutation_parser

I just have a question about the results. I noticed the overall alignment rate is ~45%. Is that expected? Is there a range for good samples?

**Comment by Psirving** [comment]
There are a lot of factors that go into alignment rate depending on the type of library prep you're using. If you are using a targeted amplicon approach, low alignment could be due to off-target priming, low Q scores from sequencing, or overlapping barcodes with another sample. With a random priming approach, the alignment rate will mostly depend on the sequence abundance in your RNA pool.

**Comment by AbeerMM** [comment]
> With a random priming approach, the alignment rate will mostly depend on the sequence abundance in your RNA pool.

@Psirving That makes sense. The libraries are prepped using Nextera + random primer. In that case, is there anything we can do to optimize for that? (in terms of the library prep). Sorry, I'm more on the computational side. Not very familiar with Shape experiments.

**Comment by Psirving** [comment]
It depends on your RNA of interest. At 45%, you are probably either already enriching your target very efficiently, or you are looking at the LSU rRNA.
