### ISSUE TITLE
Reactivity profile calculation for two samples (Modified & Untreated)

### ISSUE THREAD

**Issue by Valentine022** [Weeks-UNC/shapemapper2#43]
Hi,

I am looking at the "Reacitvity_profile" column in the *.profiles.txt file however these values do not match the y axis of the reactivity profile plot generated. How is this calculated?

Thanks!

**Comment by Psirving** [comment]
The column used in the *profiles.pdf figure is "Norm_profile". Here's a link to the documentation on this:
https://github.com/Weeks-UNC/shapemapper2/blob/master/docs/analysis_steps.md#reactivity-profile-calculation-and-normalization
