### ISSUE TITLE
Access to 2.2 update

### ISSUE THREAD

**Issue by catherine-douds** [Weeks-UNC/shapemapper2#45]
After reading the recent Mitchell et al paper (NAR 2023) I was hoping to use the -dms flag available in version 2.2. The paper link sends me here, but I don't see where to access the new version

**Comment by lucaskearns** [comment]
You can navigate to [https://github.com/Weeks-UNC/shapemapper2/releases](https://github.com/Weeks-UNC/shapemapper2/releases) and click shapemapper2-2.2.tar.gz.

Additionally, running "wget https://github.com/Weeks-UNC/shapemapper2/releases/download/2.2.0/shapemapper2-2.2.tar.gz" from command line will also download shapemapper 2.2.

Feel free to reach out if you run into any further problems.
