### ISSUE TITLE
SuperFold

### ISSUE THREAD

**Issue by xfliu1995** [Weeks-UNC/shapemapper2#7]
http://www.chem.unc.edu/rna/software.html
Page not found.
Can you give me a new address to download the software?

**Comment by shapemapper** [comment]
This link should work: https://weeks.chem.unc.edu/software.html

Who sent you/where did you find the broken link?
________________________________

**Comment by xfliu1995** [comment]
> This link should work: https://weeks.chem.unc.edu/software.html
> 
> Who sent you/where did you find the broken link?
> …

Thanks. I read it in the article，Pervasive Regulatory Functions of mRNA Structure Revealed by High-Resolution SHAPE Probing.

**Comment by shapemapper** [comment]
This is an ongoing issue with UNC's web hosting.
